
import java.util.Arrays;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David Kapanga
 */
public class RationalAssignment extends javax.swing.JFrame {
    
     static Rational[] tabr1=new Rational[10];
     static Rational[] tabr2=new Rational[10];
     static Rational[] tabr3=new Rational[10];
     static Rational[] tabr3NonSorted=new Rational[10];
     String out="";
     String arit="";

    /**
     * Creates new form RationalAssignment
     */
    public RationalAssignment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTextArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Rational ");
        setMinimumSize(new java.awt.Dimension(352, 287));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(351, 286));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(351, 286));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setEnabled(false);

        displayTextArea.setEditable(false);
        displayTextArea.setColumns(20);
        displayTextArea.setRows(5);
        jScrollPane1.setViewportView(displayTextArea);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 310, 150));

        jPanel3.setOpaque(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("*");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("/");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Sort");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 340, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsrc/close.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 30, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsrc/backGround.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(351, 286));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        out="";
        for(int i=0;i<10;i++)
        {
            int num1,num2;
            do{
                num1=(int)(Math.random()*(9-1+1)+1);
                num2=(int)(Math.random()*(9-1+1)+1);
            }while(num1==num2);
            if(num1>=num2)
            {
                tabr1[i]=new Rational(num2,num1);
            }else{
                tabr1[i]=new Rational(num1,num2);                
            }
            do{
                num1=(int)(Math.random()*(9-1+1)+1);
                num2=(int)(Math.random()*(9-1+1)+1);
            }while(num1==num2);
            if(num1>=num2)
            {
                tabr2[i]=new Rational(num2,num1);
            }else{
                tabr2[i]=new Rational(num1,num2);                
            }            
            out+= tabr1[i].getPrint() + "     +       " + tabr2[i].getPrint() + "   =   \n";
            
        }
        this.displayTextArea.setText(out);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       out="";
       arit="+";
       if(tabr1[0]!=null){
        for(int i=0;i<10;i++)
        {
            tabr3[i]=tabr1[i].add(tabr2[i]);
            out+= tabr1[i].getPrint() + "     +       " + tabr2[i].getPrint() + "   =   "+tabr3[i].getPrint()+"\n";
        }
       this.displayTextArea.setText(out);
       }
       else
       {
           out+="Error!!! \n";
           out+="Generate Rational first\nThen click on '"+arit+"' to do the operation";
           this.displayTextArea.setText(out);
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        out="";
       arit="-";       
       if(tabr1[0]!=null){
        for(int i=0;i<10;i++)
        {
            tabr3[i]=tabr1[i].sub(tabr2[i]);
            out+= tabr1[i].getPrint() + "     -       " + tabr2[i].getPrint() + "   =   "+tabr3[i].getPrint()+"\n";
        }
       this.displayTextArea.setText(out);
       }
       else
       {
           out+="Error!!! \n";
           out+="Generate Rational first\nThen click on '"+arit+"' to do the operation";
           this.displayTextArea.setText(out);
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        out="";        
       arit="*";
       if(tabr1[0]!=null){
        for(int i=0;i<10;i++)
        {
            tabr3[i]=tabr1[i].multiply(tabr2[i]);
            out+= tabr1[i].getPrint() + "     *       " + tabr2[i].getPrint() + "   =   "+tabr3[i].getPrint()+"\n";
        }
       this.displayTextArea.setText(out);
       }
       else
       {
           out+="Error!!! \n";
           out+="Generate Rational first\nThen click on '"+arit+"' to do the operation";
           this.displayTextArea.setText(out);
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       out="";       
       arit="/";
       if(tabr1[0]!=null){
        for(int i=0;i<10;i++)
        {
            tabr3[i]=tabr1[i].divide(tabr2[i]);
            out+= tabr1[i].getPrint() + "     /       " + tabr2[i].getPrint() + "   =   "+tabr3[i].getPrint()+"\n";
        }
       this.displayTextArea.setText(out);
       }
       else
       {
           out+="Error!!! \n";
           out+="Generate Rational first\nThen click on '"+arit+"' to do the operation";
           this.displayTextArea.setText(out);
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        if(tabr1[0]!=null && tabr3[0]!=null){
        out="Result r3 sorted in the last column \n"; 
        for(int i=0;i<10;i++)
        {
            if(tabr3NonSorted[i]==null)
            tabr3NonSorted[i]=tabr3[i];
        }
        for (int i = (tabr3.length - 1); i >= 0; i--)
        {
            for(int j = 1; j <= i; j++)
            {
                if(tabr3[j-1].greaterThan(tabr3[j]))
                {
                    Rational temp = tabr3[j-1];
                    tabr3[j-1] = tabr3[j];
                    tabr3[j] = temp;
                }
            }            
        }        
        for(int i=0;i<10;i++)
        {
            out+= tabr1[i].getPrint() + "     "+arit+"       " + tabr2[i].getPrint() + "   =   "+tabr3NonSorted[i].getPrint()+"    |     "+tabr3[i].getPrint()+"\n";
        }
        //the append method brings text in the new line as i used \n previously, that is 
        //why i reused setText()
       this.displayTextArea.setText(out);
        }
       else
       {
           out="Error!!!\n";
           out+="Generate Rational first\nClick on one of the operations\nThen you can click on sort to sort the result\n";
           out+="THANKS :)\n";
           this.displayTextArea.setText(out);
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RationalAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RationalAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RationalAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RationalAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        Rational r=new Rational(4,7);
        Rational r2=new Rational(1,2);
        Rational r3=r.add(r2);
        //System.out.println(r3.getPrint());
        //System.out.println(r3.isEquals(r));
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RationalAssignment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea displayTextArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
